
version: 2

models:
  - name: orders_cleaned
    description: "A cleaned version of the orders table"
    tests:
      - no_duplicates
    columns:
      - name: order_id
        data_tests:
          - not_null
      - name: listing_id
        data_tests:
          - not_null
  - name: listing_cleaned
    description: "A cleaned version of the listing table" 
    tests:
      - no_duplicates
    columns:
      - name: id
        data_tests:
          - not_null
  # TODO refine these later
  - name: orders_daily_cleaned
    description: "A cleaned version of the orders_daily_cleaned table" 
    tests:
      - no_duplicates

  - name: org_cleaned
    description: "A cleaned version of the org table" 
    tests:
      - no_duplicates
  - name: outlet_cleaned
    description: "A cleaned version of the outlet table" 
    tests:
      - no_duplicates
  - name: platform_cleaned
    description: "A cleaned version of the platform table" 
    tests:
      - no_duplicates

  - name: rank_cleaned
    description: "A cleaned version of the rank table" 
    tests:
      - no_duplicates
    columns:
      - name: timestamp
        data_tests:
          - not_null
      - name: listing_id
        data_tests:
          - not_null
      - name: date
        data_tests:
          - not_null

  - name: ratings_agg_cleaned
    description: "A cleaned version of the ratings_agg table" 
    tests:
      - no_duplicates